### ISSUE TITLE
Failover Cluster Well Known Key

### ISSUE THREAD

**Issue by ruddj** [sntcz/Clear-MachineKeys#1]
Please add well known key for Failover Cluster communication
"4f692a7dc1b824e1f679f93fadd08a3b_$machineGuid", Failover Cluster (ClusInfraCert).

https://learn.microsoft.com/en-us/answers/questions/293983/accidentally-deleted-rsa-machine-key-from-one-clus

Thanks,
 James

**Comment by tkouba** [comment]
Added
